# Generated by Django 4.1.5 on 2023-02-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='band_logos/')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_photo', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('member_name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_photo', models.ImageField(blank=True, null=True, upload_to='merch_photos/')),
                ('merch_name', models.CharField(max_length=255)),
                ('merch_description', models.TextField(blank=True)),
                ('merch_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('tour_date', models.DateTimeField()),
                ('tour_location', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-tour_date',),
            },
        ),
        migrations.CreateModel(
            name='TrackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('track_id', models.IntegerField()),
                ('slug', models.SlugField()),
                ('album_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_list', to='bandapp.album')),
            ],
        ),
    ]
