# Generated by Django 4.1.5 on 2023-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_art/'),
        ),
    ]
