# Generated by Django 4.1.5 on 2023-02-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0002_tour_tour_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name_plural': 'Merch'},
        ),
        migrations.AlterModelOptions(
            name='tracklist',
            options={'verbose_name_plural': 'Tracklist'},
        ),
    ]
