# Generated by Django 4.1.5 on 2023-02-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0003_delete_members_alter_merch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='merch_price',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
