# Generated by Django 4.1.5 on 2023-02-20 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0005_alter_tour_tour_image_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracklist',
            name='album_title',
        ),
        migrations.RemoveField(
            model_name='tracklist',
            name='song_name',
        ),
        migrations.RemoveField(
            model_name='tracklist',
            name='track_id',
        ),
        migrations.AddField(
            model_name='tracklist',
            name='album',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracklist', to='bandapp.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='album_coverart/'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('youtube_video_id', models.CharField(max_length=255)),
                ('track_id', models.IntegerField()),
                ('tracklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='bandapp.tracklist')),
            ],
        ),
    ]
