# Generated by Django 4.1.5 on 2023-02-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0006_remove_tracklist_album_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracklist',
            name='slug',
        ),
    ]
