# Generated by Django 4.1.5 on 2023-02-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0007_remove_tracklist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='track_id',
        ),
    ]
